config/routes.rb
Claregal::Application.routes.draw do

  root 'static_pages#index'

  match '/new_subscriber',     to: 'subscribers#create',      via: 'post'

  match '/signup',             to: 'users#new',               via: 'get'
  match '/signin',             to: 'sessions#new',            via: 'get'
  match '/signout',            to: 'sessions#destroy',        via: 'delete'
  match '/joinlawfirm',        to: 'lawfirm_sessions#new',    via: 'get'   #route for joinin lawfirm
  match '/joinlawfirm/commit', to: 'lawfirm_sessions#create', via: 'post'


  #----------------------------------------------------------------------#
  get '/settlement_calculators', to: "settlement_calculators#calculate", as: :calculate

  resources :sessions,                only: [:new, :create, :destroy]
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: [:new, :create, :edit, :update]
  resources :lawfirm_password_resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :lawfirms do
      member do
        get :index_lawfirm_users
        post :toggle_dashboard
      end
      resources :practicegroups do
        member do
          get :group_case_list
        end
      end
      resources :staffings
      resources :case_types
      resources :overheads
    end
  end
  match '/staffings/import',    to: "staffings#import_staffing", via: 'post'
  match '/clients/import',      to: "clients#import_clients",    via: 'post'
  match '/matter_types/import', to: "case_types#import_matters", via: 'post'

  resources :clients do
    resources :cases do
      resources :staffs
      resources :fees
      resources :timings
      resources :originations
      resources :venues
      resources :checks
      resources :closeouts
      resources :matters
      resources :related_cases
    end
  end

  match '/new_case',               to: 'cases#new_case',          via: 'get' #for creating a new case directly, more ux friendly
  match '/new_case/create',        to:'cases#create_case',        via: 'get' #same as above
  match '/new_case/create',        to:'cases#create_case',        via: 'post' #same as above
  match '/new_closed_case',        to: 'cases#new_closed_case',   via: 'get' #for creating a new closed case directly, more ux friendly
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'get' #same as above
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'post' #same as above

  match '/lawfirm/cases',          to: 'lawfirms#show_lawfirm_cases', via: 'get' #to show current_user.lawfirm.cases
  match '/user/cases',             to:  'cases#user_cases',       via: 'get' #show all cases of current_user
#--------------------------Actual GRAPH ROUTES----------------------------------------------------

  get   'dashboard',                               to: "graphs#dashboard"

  resources :graph_actuals do
    member do
      get :revenue_by_year
      get :revenue_by_pg
      get :revenue_by_fee_type
      get :revenue_by_origination
      get :revenue_by_client
      get :closed_case_load_by_year
      get :individual_practice_group
      get "/revenue_by_month/:year/", to: :revenue_by_month, as: "revenue_by_month"
      get :revenue_by_attorney
    end
  end

  #--------------------------Expected GRAPH ROUTES----------------------------------------------------
  resources :graphs do
    member do
      get :revenue_by_client_estimate
      get :revenue_by_attorney_estimate
      get :practice_group_revenue_pie_low
    end
  end

  match '/practice_group/cases',                   to: "graphs#practice_group_pie",             via: 'get'
  match '/practice_group/:id/revenue',             to: "graph_individual_prac_groups#expected_individual_pg_rev", as: 'expected_individual_pg_rev', via: 'get'

  match '/revenue_by_year/practice_group',         to: "graphs#rev_by_year_by_pg",          via: 'get'
  match '/revenue_by_year/practice_group/high',    to: "graphs#rev_by_year_by_pg_high",     via: 'get'
  match '/revenue_by_year/practice_group/low',     to: "graphs#rev_by_year_by_pg_low",      via: 'get'

  match '/revenue_by_year/fee_type/medium',        to: 'graphs#rev_by_fee_type_medium',     via: 'get'
  match '/revenue_by_year/fee_type/high',          to: 'graphs#rev_by_fee_type_high',       via: 'get'
  match '/revenue_by_year/fee_type/low',           to: 'graphs#rev_by_fee_type_low',        via: 'get'

  match '/revenue_by_origination',                 to: 'graphs#fee_received_by_referral_medium', via: 'get'


  match '/revenue_by_year',                 to: 'graph_drilldowns#rev_by_year',             via: 'get'
  match '/revenue_year',                    to: 'graph_drilldowns#rev_year',                via: 'get'

  #I do not know why this is here, but when I remove it everything breaks
  match '/revenue_by_referral_source',      to: 'graphs#rev_by_fee_type_medium',            via: 'get'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :case
  belongs_to :staffing

  validates :staffing_id, presence: true

  def self.case_total_hours_actual(case_id)
    hours_actual = 0
    staff_ids  = Staff.where(case_id: case_id).collect(&:staffing_id).uniq
    for id in staff_ids
      if Staff.where(case_id: case_id,
                    staffing_id: id).order(:updated_at).last.hours_actual != nil
        hours_actual += Staff.where(case_id: case_id,
                                    staffing_id: id).order(:updated_at).last.hours_actual
      else
        next
      end
    end
    return hours_actual
  end

  def self.case_total_hours_expected(case_id)
    hours_expected = 0
    staff_ids  = Staff.where(case_id: case_id).collect(&:staffing_id).uniq
    for id in staff_ids
      if Staff.where(case_id: case_id,
                        staffing_id: id).order(:updated_at).last.hours_expected != nil
        hours_expected += Staff.where(case_id: case_id, staffing_id: id).order(:updated_at).last.hours_expected
      else
        next
      end
    end
    return hours_expected
  end

  def self.staff_total_hours_actual(case_id,staffing_id)
    if Staff.where(:case_id => case_id, :staffing_id => staffing_id).last.hours_actual
      return Staff.where(:case_id => case_id, :staffing_id => staffing_id).last.hours_actual
    else
      return 0
    end
  end

  def self.staff_total_hours_expected(case_id, staffing_id)
    if Staff.where(:case_id => case_id, :staffing_id => staffing_id).last.hours_expected
      return Staff.where(:case_id => case_id, :staffing_id => staffing_id).last.hours_expected
    else
      return 0
    end
  end

end

app/controllers/staffs_controller.rb
#Staffing refers to actual Staff for the lawfirm
#Staff refers to Case Staff... staff that work on a case
class StaffsController < ApplicationController
  before_action :signed_in_user, :belongs_to_firm

  def index
    @client = Client.find(params[:client_id])
    @case = Case.find(params[:case_id])
    @staff = @case.staff
    #to create bargraph of actual vs expected
    @actual_hours = Staff.case_total_hours_actual(@case.id)
    @expected_hours = Staff.case_total_hours_expected(@case.id)
    @last_update = StaffCase.case_last_update(@case.id)
  end

  def new
    @lawfirm = current_user.lawfirm
    @case = Case.find(params[:case_id])
    @client = Client.find(params[:client_id])
    @staff = Staff.new
  end

  def create
    @client = Client.find(params[:client_id])
    @case = Case.find(params[:case_id])
    @staff = @case.staff.new(staff_params)
    #@staff.staffing_id will cause problems when a lawfirm has people witht the same first and last name
    if @staff.save
      #add record to StaffCase because StaffCase is Master Record of all Case Staff
      StaffCase.create!(staffing_id: @staff.staffing_id, case_id: @case.id, current_case: true,
                    hours_expected: @staff.hours_expected || nil,
                    hours_actual: @staff.hours_actual || nil)
      flash[:success] = "Staff Added Successfully"
      #where should we go from here?
      redirect_to client_case_staffs_path(@client, @case)
    else
      render 'new'
    end
  end

  def show
    @lawfirm = current_user.lawfirm
    @staff = Staff.find(params[:id])
    @case = Case.find(params[:case_id])
    @client = Client.find(params[:client_id])
  end

  def edit
    @lawfirm = current_user.lawfirm
    @staff = Staff.find(params[:id])
    @case = Case.find(params[:case_id])
    @client = Client.find(params[:client_id])
  end

  def update
    @staff = Staff.find(params[:id])
    @case = Case.find(params[:case_id])
    @client = Client.find(params[:client_id])
    if @staff.update_attributes(staff_params)
      #add record to StaffCase because StaffCase is Master Record of all Case Staff
      StaffCase.create!(staffing_id: @staff.staffing_id, case_id: @case.id, current_case: true,
                      hours_expected: @staff.hours_expected || nil,
                      hours_actual: @staff.hours_actual || nil)
      flash[:success] = "Staff Updated Successfully"
      redirect_to client_case_staffs_path(@client, @case)
    else
      render 'edit'
    end
  end

  def destroy
    @case = Case.find(params[:case_id])
    @client = Client.find(params[:client_id])
    @staff = Staff.find(params[:id])
    @staff.destroy
    #add record to StaffCase because StaffCase is Master Record of all Case Staff
    StaffCase.create!(staffing_id: @staff.staffing_id, case_id: @case.id, current_case: false,
                      hours_expected: @staff.hours_expected || nil,
                      hours_actual: @staff.hours_actual || nil)
    flash[:success] = "Staff Removed Successfully"
    redirect_to client_case_staffs_path(@client, @case)
  end

  private

    def staff_params
      params.require(:staff).permit(:name, :staffing_id, :position, :percent_utilization, :hours_expected, :hours_actual)
    end

end

app/views/staffs/edit.html.erb
<% provide(:title, 'Update Staff') %>

<%= render 'shared/subheader' %>

<h2>Update Case Staff</h2>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_for(@staff, url: {action: "update"}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <table class="table">
          <tr>
            <td><%= f.label "Name:" %></td>
            <td><%=f.collection_select(:staffing_id, current_user.lawfirm.staffings.order(:last_name).all, :id, :full_name_last_first, :include_blank => "Select") %></td>
          </tr>
          <tr>
            <td><%= f.label "Position:" %></td>
            <td><%=f.select(:position, Staffing.all_positions(current_user).sort, :include_blank => "Select") %></td>
          </tr>
          <tr>
            <td><%= f.label "Expected Total Hours:" %></td>
            <td><%=f.text_field :hours_expected %></td>
          </tr>
          <tr>
            <td><%= f.label "Actual Hours Worked:" %></td>
            <td><%=f.text_field :hours_actual, :placeholder => 'Leave blank if new case' %></td>
          </tr>
        </table>

      <div class="center">
        <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
      </div>
      <% end %>
      <br>
      <br>

    <div class='center'>
      <%= link_to "Add Staff to #{@lawfirm.firm_name}", new_user_lawfirm_staffing_path(:user_id => current_user.id, :lawfirm_id => current_user.lawfirm_id) %>
    </div>

    </div>
  </div>
</div>

app/views/staffs/index.html.erb
<% provide(:title, "Staff Information") %>

<%= render 'shared/subheader' %>

<h2>Case Staff</h2>

<% if @case.staff.present? %>

<table id="caseStaff" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Expected Total Hours</th>
      <th>Actual Total Hours</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @staff.order(:name,:updated_at).each do |staf| %>
      <tr>
        <td><%= Staffing.find_by(id: staf.staffing_id).full_name_last_first %></td>
        <td><%= staf.position %></td>
        <td><%= staf.hours_expected ? staf.hours_expected : "" %></td>
        <td><%= staf.hours_actual ? staf.hours_actual : "" %></td>
        <td><%= link_to 'Update', edit_client_case_staff_path(@client,@case,staf) %></td>
        <td><%= link_to 'Remove', client_case_staff_path(@client,@case,staf), method: :delete, data: { confirm: "Remove #{Staffing.find_by(id: staf.staffing_id).full_name_last_first}?" }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<div class='center'>
  <p><%= link_to "Add More Staff", new_client_case_staff_path(@client,@case), class: 'btn btn-md btn-primary' %></p>
</div>

<div id='actualVersusExpectedBar' style="min-width: 310px;
                                      height: 600px; width: 600px;
                                      max-width: 600px;
                                       margin: 0 auto">
</div>

<script type="text/javascript">

  var expectedHours = <%= @expected_hours %>;
  var actualHours = <%= @actual_hours %>;
  var categories = "<%= "#{@last_update}" %>";
$(function () {
    $('#actualVersusExpectedBar').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Actual vs Expected Hours'
        },
        credits: {
          enabled: false
        },
        subtitle: {
            text: 'as of last update'
        },
        xAxis: {
            categories: ['Last Updated: '+ categories]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Hours'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                }
            }
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black, 0 0 3px black'
                    }
                }
            }
        },
        series: [{
            name: 'Remaining',
            data: [expectedHours-actualHours]
        }, {
            name: 'Actual Hours',
            data: [actualHours]

        }]
    });
});

</script>

app/views/staffs/new.html.erb
<% provide(:title, 'Case Staff') %>

<%= render 'shared/subheader' %>

<h2>Add Case Personnel</h2>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_for(@staff, url: {action: "create"}, html: {class: "form-horizontal"}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>


      <div class="form-group">
        <div class="col-sm-3">
          <%= f.label :name, "Name:" , class: "control-label" %>
        </div>
        <div class="col-sm-9">
          <%=f.collection_select(:staffing_id, current_user.lawfirm.staffings.order(:last_name).all, :id, :full_name_last_first, {:include_blank => "Select"}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-3">
          <%= f.label :position, "Case Position:", class: "control-label" %>
        </div>
        <div class="col-sm-9">
          <%= f.select(:position, Staffing.all_positions(current_user).sort, {:include_blank => "Select"}, {class: "form-control"}) %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-3">
          <%= f.label :hours_expected, "Expected Total Hours:", class: "control-label" %>
        </div>
        <div class="col-sm-9">
          <%= f.text_field :hours_expected, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-3">
          <%= f.label :hours_actual, "Actual Hours Worked:", class: "control-label" %>
        </div>
        <div class="col-sm-9">
          <%= f.text_field :hours_actual, class: "form-control" %>
        </div>
      </div>

    <div class='center'>
        <%= f.submit "Submit", class: "btn btn-large btn-primary" %>

      <% end %>
      <br>
      <br>

      <%= link_to "Staff name or position not found? Add Staff to #{@lawfirm.firm_name}", new_user_lawfirm_staffing_path(:user_id => current_user.id, :lawfirm_id => current_user.lawfirm_id) %>
    </div>

    </div>
  </div>
</div>

app/views/staffs/show.html.erb
<% provide(:title, "Staff Information") %>

<%= render 'shared/subheader' %>

<h1>Case Staff</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= Staffing.find_by(id: @staff.staffing_id).full_name_last_first %></td>
      <td><%= @staff.position %></td>
    </tr>
  </tbody>
</table>

<br>
<br>

<h2> <%= link_to "Edit Staff", edit_client_case_staff_path(@client, @case, @staff) %></h2>