config/routes.rb
Claregal::Application.routes.draw do

  root 'static_pages#index'

  match '/new_subscriber',     to: 'subscribers#create',      via: 'post'

  match '/signup',             to: 'users#new',               via: 'get'
  match '/signin',             to: 'sessions#new',            via: 'get'
  match '/signout',            to: 'sessions#destroy',        via: 'delete'
  match '/joinlawfirm',        to: 'lawfirm_sessions#new',    via: 'get'   #route for joinin lawfirm
  match '/joinlawfirm/commit', to: 'lawfirm_sessions#create', via: 'post'


  #----------------------------------------------------------------------#
  get '/settlement_calculators', to: "settlement_calculators#calculate", as: :calculate

  resources :sessions,                only: [:new, :create, :destroy]
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: [:new, :create, :edit, :update]
  resources :lawfirm_password_resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :lawfirms do
      member do
        get :index_lawfirm_users
        post :toggle_dashboard
      end
      resources :practicegroups do
        member do
          get :group_case_list
        end
      end
      resources :staffings
      resources :case_types
      resources :overheads
    end
  end
  match '/staffings/import',    to: "staffings#import_staffing", via: 'post'
  match '/clients/import',      to: "clients#import_clients",    via: 'post'
  match '/matter_types/import', to: "case_types#import_matters", via: 'post'

  resources :clients do
    resources :cases do
      resources :staffs
      resources :fees
      resources :timings
      resources :originations
      resources :venues
      resources :checks
      resources :closeouts
      resources :matters
      resources :related_cases
    end
  end

  match '/new_case',               to: 'cases#new_case',          via: 'get' #for creating a new case directly, more ux friendly
  match '/new_case/create',        to:'cases#create_case',        via: 'get' #same as above
  match '/new_case/create',        to:'cases#create_case',        via: 'post' #same as above
  match '/new_closed_case',        to: 'cases#new_closed_case',   via: 'get' #for creating a new closed case directly, more ux friendly
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'get' #same as above
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'post' #same as above

  match '/lawfirm/cases',          to: 'lawfirms#show_lawfirm_cases', via: 'get' #to show current_user.lawfirm.cases
  match '/user/cases',             to:  'cases#user_cases',       via: 'get' #show all cases of current_user
#--------------------------Actual GRAPH ROUTES----------------------------------------------------

  get   'dashboard',                               to: "graphs#dashboard"

  resources :graph_actuals do
    member do
      get :revenue_by_year
      get :revenue_by_pg
      get :revenue_by_fee_type
      get :revenue_by_origination
      get :revenue_by_client
      get :closed_case_load_by_year
      get :individual_practice_group
      get "/revenue_by_month/:year/", to: :revenue_by_month, as: "revenue_by_month"
      get :revenue_by_attorney
    end
  end

  #--------------------------Expected GRAPH ROUTES----------------------------------------------------
  resources :graphs do
    member do
      get :revenue_by_client_estimate
      get :revenue_by_attorney_estimate
      get :practice_group_revenue_pie_low
    end
  end

  match '/practice_group/cases',                   to: "graphs#practice_group_pie",             via: 'get'
  match '/practice_group/:id/revenue',             to: "graph_individual_prac_groups#expected_individual_pg_rev", as: 'expected_individual_pg_rev', via: 'get'

  match '/revenue_by_year/practice_group',         to: "graphs#rev_by_year_by_pg",          via: 'get'
  match '/revenue_by_year/practice_group/high',    to: "graphs#rev_by_year_by_pg_high",     via: 'get'
  match '/revenue_by_year/practice_group/low',     to: "graphs#rev_by_year_by_pg_low",      via: 'get'

  match '/revenue_by_year/fee_type/medium',        to: 'graphs#rev_by_fee_type_medium',     via: 'get'
  match '/revenue_by_year/fee_type/high',          to: 'graphs#rev_by_fee_type_high',       via: 'get'
  match '/revenue_by_year/fee_type/low',           to: 'graphs#rev_by_fee_type_low',        via: 'get'

  match '/revenue_by_origination',                 to: 'graphs#fee_received_by_referral_medium', via: 'get'


  match '/revenue_by_year',                 to: 'graph_drilldowns#rev_by_year',             via: 'get'
  match '/revenue_year',                    to: 'graph_drilldowns#rev_year',                via: 'get'

  #I do not know why this is here, but when I remove it everything breaks
  match '/revenue_by_referral_source',      to: 'graphs#rev_by_fee_type_medium',            via: 'get'

end

app/models/lawfirm.rb
class Lawfirm < ActiveRecord::Base
  has_many :users
  has_many :practicegroups
  has_many :staffings
  has_many :clients, through: :users
  has_many :cases, through: :clients
  has_many :case_types
  has_many :originations, through: :cases
  has_many :overheads

  attr_accessor :reset_token

  validates :firm_name, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  #set password reset attributes
  def create_reset_digest
    self.reset_token = Lawfirm.new_token
    update_attribute(:reset_digest, Lawfirm.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

    #Return true if password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

end

app/controllers/lawfirms_controller.rb
class LawfirmsController < ApplicationController
  before_action :signed_in_user

  def new
    @lawfirm = Lawfirm.new
    @user = User.find(params[:user_id])
  end

  def create #on creation, need to add lawfirm_id to the user index
    @lawfirm = Lawfirm.new(lawfirm_params)
    @user = User.find(params[:user_id])
    if @lawfirm.save
      flash[:success] = "#{@lawfirm.firm_name} created successfully"
      @user.update_attribute(:lawfirm_id, @lawfirm.id)
      @lawfirm.update_attribute(:user_id, current_user.id)
      redirect_to user_cases_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @lawfirm = Lawfirm.find(params[:id])
  end

  def update
    @lawfirm = Lawfirm.find(params[:id])
    if @lawfirm.authenticate(params[:old_password][:old_password])
      if @lawfirm.update_attributes(lawfirm_params)
        flash[:success] = "Firm Updated Successfully"
        redirect_to index_lawfirm_users_user_lawfirm_path(current_user.id, current_user.lawfirm.id)
      else
        flash[:danger] = "Fix the following errors."
        render 'edit'
      end
    else
      flash[:danger] = "Password is incorrect"
      render 'edit'
    end
  end

  def show
    @lawfirm = Lawfirm.find(params[:id])
  end

  def index
    @firm_name = current_user.lawfirm.firm_name
    @lawfirm_clients = current_user.lawfirm.clients.order(:last_name).load
  end

  def show_lawfirm_cases
    @firm_name = current_user.lawfirm.firm_name
    @lawfirm_cases = current_user.lawfirm.cases.load  #this is the paginate form
  end

  # Allow lawfirm creator to have admin access to who views what
  def index_lawfirm_users
    if current_user.id == current_user.lawfirm.user_id
      @users = User.where(lawfirm_id: current_user.lawfirm.id).load
    else
      flash[:danger] = "You must have administrative privileges to view this page."
      redirect_to user_cases_path
    end
  end

  #Lawfirm Admin grants access to lawfirm users to view dashboard
  def toggle_dashboard
    user = User.find(params[:id])
    if params[:dashboard_access] == "true" && user.dashboard_access == false || user.dashboard_access == nil
      respond_to do |format|
        if user.update_attribute(:dashboard_access, 1)
          format.html { render :nothing => true, :notice => "Updated Dashboard Access."}
          format.js { render :nothing => true, :notice => "Updated Dashboard Access"}
        else
          @users = User.where(lawfirm_id: current_user.lawfirm.id).load
          format.html { render :action => 'index_lawfirm_users', :notice => "We were not able to offer dashboard access at this time.  Please email admin@clarlegal.com if this persists." }
          format.js { render :action => 'index_lawfirm_users', :notice => "We were not able to offer dashboard access at this time.  Please email admin@clarlegal.com if this persists."}
        end
      end
    elsif params[:dashboard_access] == "false" && user.dashboard_access == true || user.dashboard_access = nil
      respond_to do |format|
        if user.update_attribute(:dashboard_access, 0)
          format.html { render :nothing => true, :notice => "Updated Dashboard Access."}
          format.js { render :nothing => true, :notice => "Updated Dashboard Access"}
        else
          @users = User.where(lawfirm_id: current_user.lawfirm.id).load
          format.html { render :action => 'index_lawfirm_users', :notice => "We were not able to offer dashboard access at this time.  Please email admin@clarlegal.com if this persists." }
          format.js { render :action => 'index_lawfirm_users', :notice => "We were not able to offer dashboard access at this time.  Please email admin@clarlegal.com if this persists."}
        end
      end
    end
  end

  private

    def lawfirm_params
      params.require(:lawfirm).permit(:firm_name, :password, :password_confirmation, :user_id)
    end

end

app/views/lawfirms/edit.html.erb
<% provide(:title, 'Edit Firm') %>
<h2><%= "Edit Information - #{@lawfirm.firm_name} " %></h2>

<div class='container'>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <%= form_for(@lawfirm, url: {action: "update"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <table class="table">
        <tr>
          <td><%= f.label :firm_name, "Law Firm Name:" %></td>
          <td><%= f.text_field :firm_name %></td>
        </tr>
        <tr>
          <td><%= label :old_password, "Old Password:" %></td>
          <td><%= password_field :old_password, :old_password %></td>
        </tr>
        <tr>
          <td><%= f.label :password, "Password:" %></td>
          <td><%= f.password_field :password, :placeholder => "Be sure to write this down for other firm members." %></td>
        </tr>
        <tr>
          <td><%= f.label :password_confirmation, "Password Confirmation" %></td>
          <td><%= f.password_field :password_confirmation, :placeholder => "And keep separate from your user password." %></td>
        </tr>
      </table>
      <div class="center">
        <%= f.submit "Update Firm", class: "btn btn-large btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lawfirms/index.html.erb
<% provide(:title, 'Firm Clients') %>

<h2><%= "Clients of #{@firm_name}" %></h2>


<table id="lawfirmClients" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
      <% @lawfirm_clients.each do |client| %>

      <!-- Use Client.company first, otherwise use client.full_name -->
        <% if client.company %>
          <% client.company.blank? ? name = client.full_name_last_first : name = client.company %>
        <% else %>
          <% client.company == nil ? name = client.full_name_last_first : name = "Need a name" %>
        <% end %>
      <!-- End name set -->

        <tr>
          <td><%= link_to name, client_path(client) %></td>
          <td><%= client.email %></td>
          <td><%= client.phone_number %></td>
          <td><%= client.street_address %><br>
              <%= client.city%>, <%=client.state%>, <%=client.zip_code %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

  <div class="center">
   <%= link_to 'Add a Client', new_client_path, class: 'btn btn-md btn-primary' %>
  </div>

app/views/lawfirms/index_lawfirm_users.html.erb
<% provide(:title, 'Firm Users') %>

<h2><%= "Members of #{current_user.lawfirm.firm_name}" %></h2>


<table id="lawfirmUsers" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Dashboard Access?</th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.full_name_last_first %></td>
          <td><%= user.email %></td>
          <td><%= check_box_tag("dashboard",user.id, user.dashboard_access, class: 'dashboard-access', data: {remote: true}) %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<div class="center">
  <%= link_to "Change Firm Password", edit_user_lawfirm_path(current_user.id,current_user.lawfirm.id), class: "btn btn-md btn-primary" %>
  <%= link_to "Forgot Firm Password?", new_lawfirm_password_reset_path, class: "btn btn-md btn-danger" %>
</div>

<script type="text/javascript">
  $('.dashboard-access').on('change', function() {
    $.ajax({
      url: "/users/" + <%=current_user.id %> + "/lawfirms/" + this.value + "/toggle_dashboard",
      type: 'POST',
      data: {"dashboard_access": this.checked}
    });
  });
</script>

app/views/lawfirms/new.html.erb
<!-- ISSUE ON INTERNET EXPLORER UPON SUBMIT CLICK...REVIEW HEROKU LOGS -->

<% provide(:title, 'Add Law Firm') %>
<h1>Add Law Firm</h1>

<div class='container'>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="center">
        <p>Does your law firm already have an account with ClarLegal?</p>
        <%= link_to "Click Here", joinlawfirm_path, class: 'btn btn-sm btn-primary' %>
      </div>
    <br>
    <br>
    <%= form_for(@lawfirm, url: {action: "create"}, html: {class: "form-horizontal"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <div class="">
              <td><%= f.label :firm_name, "Firm Name:", class: "control-label col-sm-3" %></td>
            </div>
            <div class='col-sm-6'>
              <td><%= f.text_field :firm_name, class: "form-control" %></td>
            </div>
          </div>

          <div class="form-group">
            <div class="">
              <td><%= f.label :password, class: "control-label col-sm-3" %></td>
            </div>
            <div class='col-sm-6'>
              <td><%= f.password_field :password, class: "form-control", :placeholder => "Be sure to write this down for other firm members." %></td>
            </div>
          </div>

          <div class="form-group">
            <div class="">
              <td><%= f.label :password_confirmation,"Password Confirmation", class: "control-label col-sm-3" %></td>
            </div>
            <div class='col-sm-6'>
              <td><%= f.password_field :password_confirmation, class: "form-control", :placeholder => "And keep separate from your user password." %></td>
            </div>
          </div>

      <div class="center">
        <%= f.submit "Create Firm", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/lawfirms/show.html.erb
<h1>Lawfirms#show</h1>
<p>Find me in app/views/lawfirms/show.html.erb</p>

app/views/lawfirms/show_lawfirm_cases.html.erb
<% provide(:title, 'Cases') %>

<h2><%= "#{@firm_name} Case List" %></h2>

<table id="lawfirmCases" class="display">
  <thead>
    <tr>
      <th>Case Name<br>
        (click to view)</th>
      <th>Practice Group</th>
      <th>Client Name</th>
      <th>Responsible Attorney</th>
      <th>Judge</th>
      <th>Opposing Counsel</th>
      <th>Case Number</th>
    </tr>
  </thead>
  <tbody>
      <% @lawfirm_cases.each do |one_case| %>
       <tr>
        <td><%= link_to one_case.name != nil && one_case.name != "" ? one_case.name : "Add Name", client_case_path(:client_id => one_case.client_id, :id => one_case.id) %></td>
        <td><%= Practicegroup.find_by(id: one_case.practicegroup_id).group_name %> </td>
        <td><%= one_case.client.company ? one_case.client.company.empty? ? one_case.client.full_name_last_first : one_case.client.company : one_case.client.company%> </td>
        <td><%= Case.lead_attorney(one_case).blank? ? "Select a primary attorney" : Case.lead_attorney(one_case) %></td>
        <td><%= one_case.judge ? one_case.judge : "" %></td>
        <td><%= one_case.opposing_attorney ? one_case.opposing_attorney : ""%></td>
        <td><%= one_case.case_number ? one_case.case_number : "" %></td>
      <% end %>
  </tbody>
</table>

  <div class="center">
    <%= link_to "Add Open Case", new_case_path, class: 'btn btn-md btn-primary' %>
    <%= link_to "Add Closed Case", new_closed_case_path, class: 'btn btn-md btn-primary' %>
  </div>