config/routes.rb
Claregal::Application.routes.draw do

  root 'static_pages#index'

  match '/new_subscriber',     to: 'subscribers#create',      via: 'post'

  match '/signup',             to: 'users#new',               via: 'get'
  match '/signin',             to: 'sessions#new',            via: 'get'
  match '/signout',            to: 'sessions#destroy',        via: 'delete'
  match '/joinlawfirm',        to: 'lawfirm_sessions#new',    via: 'get'   #route for joinin lawfirm
  match '/joinlawfirm/commit', to: 'lawfirm_sessions#create', via: 'post'


  #----------------------------------------------------------------------#
  get '/settlement_calculators', to: "settlement_calculators#calculate", as: :calculate

  resources :sessions,                only: [:new, :create, :destroy]
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: [:new, :create, :edit, :update]
  resources :lawfirm_password_resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :lawfirms do
      member do
        get :index_lawfirm_users
        post :toggle_dashboard
      end
      resources :practicegroups do
        member do
          get :group_case_list
        end
      end
      resources :staffings
      resources :case_types
      resources :overheads
    end
  end
  match '/staffings/import',    to: "staffings#import_staffing", via: 'post'
  match '/clients/import',      to: "clients#import_clients",    via: 'post'
  match '/matter_types/import', to: "case_types#import_matters", via: 'post'

  resources :clients do
    resources :cases do
      resources :staffs
      resources :fees
      resources :timings
      resources :originations
      resources :venues
      resources :checks
      resources :closeouts
      resources :matters
      resources :related_cases
    end
  end

  match '/new_case',               to: 'cases#new_case',          via: 'get' #for creating a new case directly, more ux friendly
  match '/new_case/create',        to:'cases#create_case',        via: 'get' #same as above
  match '/new_case/create',        to:'cases#create_case',        via: 'post' #same as above
  match '/new_closed_case',        to: 'cases#new_closed_case',   via: 'get' #for creating a new closed case directly, more ux friendly
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'get' #same as above
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'post' #same as above

  match '/lawfirm/cases',          to: 'lawfirms#show_lawfirm_cases', via: 'get' #to show current_user.lawfirm.cases
  match '/user/cases',             to:  'cases#user_cases',       via: 'get' #show all cases of current_user
#--------------------------Actual GRAPH ROUTES----------------------------------------------------

  get   'dashboard',                               to: "graphs#dashboard"

  resources :graph_actuals do
    member do
      get :revenue_by_year
      get :revenue_by_pg
      get :revenue_by_fee_type
      get :revenue_by_origination
      get :revenue_by_client
      get :closed_case_load_by_year
      get :individual_practice_group
      get "/revenue_by_month/:year/", to: :revenue_by_month, as: "revenue_by_month"
      get :revenue_by_attorney
    end
  end

  #--------------------------Expected GRAPH ROUTES----------------------------------------------------
  resources :graphs do
    member do
      get :revenue_by_client_estimate
      get :revenue_by_attorney_estimate
      get :practice_group_revenue_pie_low
    end
  end

  match '/practice_group/cases',                   to: "graphs#practice_group_pie",             via: 'get'
  match '/practice_group/:id/revenue',             to: "graph_individual_prac_groups#expected_individual_pg_rev", as: 'expected_individual_pg_rev', via: 'get'

  match '/revenue_by_year/practice_group',         to: "graphs#rev_by_year_by_pg",          via: 'get'
  match '/revenue_by_year/practice_group/high',    to: "graphs#rev_by_year_by_pg_high",     via: 'get'
  match '/revenue_by_year/practice_group/low',     to: "graphs#rev_by_year_by_pg_low",      via: 'get'

  match '/revenue_by_year/fee_type/medium',        to: 'graphs#rev_by_fee_type_medium',     via: 'get'
  match '/revenue_by_year/fee_type/high',          to: 'graphs#rev_by_fee_type_high',       via: 'get'
  match '/revenue_by_year/fee_type/low',           to: 'graphs#rev_by_fee_type_low',        via: 'get'

  match '/revenue_by_origination',                 to: 'graphs#fee_received_by_referral_medium', via: 'get'


  match '/revenue_by_year',                 to: 'graph_drilldowns#rev_by_year',             via: 'get'
  match '/revenue_year',                    to: 'graph_drilldowns#rev_year',                via: 'get'

  #I do not know why this is here, but when I remove it everything breaks
  match '/revenue_by_referral_source',      to: 'graphs#rev_by_fee_type_medium',            via: 'get'

end

app/views/shared/_newheader.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="logo" href="/" class="navbar-brand">CLARLEGAL</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home", signed_in? ? user_cases_path : root_path %></li>

      <% if signed_in? %>

        <% if current_user.lawfirm_id != nil %>

          <li><%= link_to "Dashboard", dashboard_path%></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tools<b class='caret'></b>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Settlement Calculator", calculate_path %>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Firm <b class='caret'>
                                                                               </b>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Clients", user_lawfirms_path(:user_id => current_user.id, :lawfirm_id => current_user.lawfirm.id) %>
              </li>
              <li>
                <%= link_to "Cases", lawfirm_cases_path %>
              </li>
              <li>
                <%= link_to "Staff", user_lawfirm_staffings_path(:user_id => current_user.id, :lawfirm_id => current_user.lawfirm.id) %>
              </li>
              <li>
                <%= link_to "Practice Groups", user_lawfirm_practicegroups_path(:user_id =>current_user.id,:lawfirm_id => current_user.lawfirm.id) %>
              </li>
              <li>
                <%= link_to "Matter Types", user_lawfirm_case_types_path(:user_id =>current_user.id,:lawfirm_id => current_user.lawfirm.id) %>
              </li>
              <% if current_user.lawfirm.overheads.last != nil %>
                <li>
                  <%= link_to "Overhead", user_lawfirm_overheads_path(:user_id =>current_user.id,:lawfirm_id => current_user.lawfirm.id ) %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Overhead", new_user_lawfirm_overhead_path(:user_id =>current_user.id,:lawfirm_id => current_user.lawfirm.id) %>
                </li>
              <% end %>
              <!-- If user.id matches lawfirm.user_id, user is admin. -->
              <% if current_user.id == current_user.lawfirm.user_id %>
                <li>
                  <%= link_to "Admin", index_lawfirm_users_user_lawfirm_path(current_user.id, current_user.lawfirm.id) %>
                </li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Join Firm", new_user_lawfirm_path(current_user.id) %></li>
        <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Clients <b class='caret'></b>
            <ul class="dropdown-menu">
              <li><%= link_to "All Clients", clients_path %></li>
              <li><%= link_to "New Client", new_client_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Cases <b class='caret'></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Cases", user_cases_path %></li>
              <li class="dropdown-submenu">
                <a href="#">Create Case</a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Open Case", new_case_path %></li>
                  <li><%= link_to "Closed Case", new_closed_case_path %></li>
                </ul>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class='caret'></b>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>



</nav>

app/views/shared/_sidebar.html.erb
  <div class="sidebar">
    <div class="col-lg-9">
      <ul class="nav nav-pills nav-stacked">

        <li class="<%=is_active_graph?("graphs","practice_group_pie") %>">
          <%= link_to "Cases by Practice Group", practice_group_cases_path %>
        </li>
        <li role='presentation'class="divider"></li>

        <li class="<%=is_active_graph?("graphs","practice_group_revenue_pie_low") %>">
          <%= link_to "Gross Fee Received by Practice Group", practice_group_revenues_path %>
        </li>
         <li role='presentation' class="divider"></li>

        <li class="<%=is_active_graph?("graphs","actual_revenue_by_year") %>">
          <%= link_to "Actual Net Fee Received by Year", revenue_by_year_actual_path %>
        </li>
         <li role='presentation' class="divider"></li>

        <li class="<%=is_active_for_drilldowns?("graph_drilldowns","rev_by_fee_type")%>">
         <%= link_to "Estimated Net Fee Received by Year", revenue_by_year_expected_path %>
       </li>
         <li class="divider"></li>

        <li class="<%=is_active_graph?("graphs","rev_by_year_by_pg") ||
                      is_active_graph?("graphs","rev_by_year_by_pg_high") ||
                      is_active_graph?("graphs","rev_by_year_by_pg_low")%>">
          <%= link_to "Estimated Gross Fee by Practice Group by Year", revenue_by_year_practice_group_path %>
        </li>
         <li class="divider"></li>

        <li class="<%=is_active_graph?("graph_drilldowns","rev_by_fee_type")%>">
          <%= link_to "Estimated Gross Fee by Fee Type", revenue_by_year_fee_type_path %>
        </li>
        <li class="divider"></li>

        <li class="<%=is_active_graph?('graphs','actual_revenue_by_referral_source')%>">
          <%= link_to "Net Fee Received by Referral Source", revenue_by_referral_source_path %>
        </li>
        <li class="divider"></li>

        <li class="<%= is_active_graph?("graph_individual_prac_groups","expected_individual_pg_rev") %> dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Practice Groups <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu" id="individualPracticeGroups">

          </ul>
        <li>
      </ul>
    </div>
  </div>

<script type="text/javascript">
  $(function () {
    <% prac_group = Graph.user_practice_groups(current_user) %>
    var allPracticeGroups = <%= raw prac_group %>;
    var allPracticeGroupIds = <%= raw Graph.user_practice_group_ids(current_user) %>
    var ulToAddTo = document.getElementById("individualPracticeGroups");
    for (var i in allPracticeGroups) {
      var pracgroupID = allPracticeGroupIds[i]
      var li = document.createElement("li");
      var a = document.createElement('a');
      var textForAElement = document.createTextNode(allPracticeGroups[i])
      a.appendChild(textForAElement)
      a.href =  "/practice_group/"+pracgroupID+"/revenue"
      li.appendChild(a);
      ulToAddTo.appendChild(li);
    };
  });


   $('ul.nav li.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(150).fadeIn();
   }, function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(150).fadeOut();
   });


</script>

app/views/shared/_sidebar_projected.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li class="">
            <a href="/dashboard"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
        </li>
        <li>
            <!-- Expected Earnings -->
        <li class="<%=is_active_for_drilldowns?("graph_drilldowns","rev_by_fee_type")%>">
          <%= link_to "Revenue/Profit by Year", revenue_by_year_path(recovery_rate: 'expected') %>
        </li>

        <li class="<%=is_active_graph?("graphs","practice_group_pie") %>">
          <%= link_to "Cases by Practice Group", practice_group_cases_path %>
        </li>

        <li class="<%=is_active_graph?("graphs","practice_group_revenue_pie_low") %>">
          <%= link_to "Fee Received by Practice Group", practice_group_revenue_pie_low_graph_path(current_user.lawfirm_id) %>
        </li>

        <li class="<%=is_active_graph?('graphs','rev_by_year_by_pg')%> or <%=is_active_graph?('graphs','rev_by_year_by_pg_high')%> or <%=is_active_graph?('graphs','rev_by_year_by_pg_low')%>">
          <%= link_to "Fee Received by Practice Group by Year", revenue_by_year_practice_group_path %>
        </li>

        <li class="<%=is_active_graph?("graphs","rev_by_fee_type_medium")%> <%=is_active_graph?("graphs","rev_by_fee_type_high")%> <%=is_active_graph?("graphs","rev_by_fee_type_low")%>">
          <%= link_to "Fee Received by Fee Type", revenue_by_year_fee_type_medium_path %>
        </li>

        <li class="<%=is_active_graph?('graphs','fee_received_by_referral_medium')%>">
          <%= link_to "Fee Received by Origination Source", revenue_by_origination_path %>
        </li>

        <li class="<%=is_active_graph?('graphs','revenue_by_client_estimate')%>">
          <%= link_to "Client Profitability", revenue_by_client_estimate_graph_path(params[:client_id] || current_user.lawfirm.clients.first, params[:timing] || "estimated_conclusion_expected") %>
        </li>

        <li class='<%= is_active_graph?("graph_individual_prac_groups","expected_individual_pg_rev") %>'>
          <a href="javascript:;" data-toggle="collapse" data-target="#practice-groups-expected" ><i class="fa fa-fw fa-arrows-v"></i>Practice Groups<i class="fa fa-fw fa-caret-down"></i></a>
          <ul id="practice-groups-expected" class="collapse">
          </ul>
        </li>

        <li class='<%= is_active_graph?("graphs","revenue_by_attorney_estimate") %>'>
          <a href="javascript:;" data-toggle="collapse" data-target="#rev-attorney-expected" ><i class="fa fa-fw fa-arrows-v"></i>Attorneys<i class="fa fa-fw fa-caret-down"></i></a>
          <ul id="rev-attorney-expected" class="collapse">
          </ul>
        </li>

            <!-- End Expected -->
    </ul>
</div>

<script type="text/javascript">
  $(function () {
    <% prac_group = Graph.user_practice_groups(current_user) %>
    var allPracticeGroups = <%= raw prac_group %>;
    var allPracticeGroupIds = <%= raw Graph.user_practice_group_ids(current_user) %>
    var ulToAddTo = document.getElementById("practice-groups-expected");
    for (var i in allPracticeGroups) {
      var pracgroupID = allPracticeGroupIds[i]
      var li = document.createElement("li");
      var a = document.createElement('a');
      var textForAElement = document.createTextNode(allPracticeGroups[i])
      a.appendChild(textForAElement)
      a.href =  "/practice_group/"+pracgroupID+"/revenue"
      li.appendChild(a);
      ulToAddTo.appendChild(li);
    };

    <% attorneys = current_user.lawfirm.staffings.order(:last_name).map {|att| att.full_name_last_first } %>;
    <% attorneyIds = current_user.lawfirm.staffings.order(:last_name).ids %>;
    var allAttorneys = <%= raw attorneys %>;
    var allAttorneyIds = <%= raw attorneyIds %>;
    var addToAttorneyUL = document.getElementById("rev-attorney-expected");
    for (var i in allAttorneys) {
      var attorneyID = allAttorneyIds[i];
      var liElement = document.createElement('li');
      var aElement = document.createElement('a');
      var newTextForAElement = document.createTextNode(allAttorneys[i]);
      aElement.appendChild(newTextForAElement);
      aElement.href = '/graphs/'+attorneyID+'/revenue_by_attorney_estimate/';
      liElement.appendChild(aElement);
      addToAttorneyUL.appendChild(liElement);
    }
  });
</script>

app/views/shared/_sidenav.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li class=''>
            <a href="/dashboard"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
        </li>
        <li>
            <!-- Actual Earnings -->
            <a href="javascript:;" data-toggle="collapse" data-target="#actual"><i class="fa fa-fw fa-arrows-v"></i> Actual Earnings <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="actual" class="collapse">
                <li class="<%=is_active_graph?("graph_actuals","revenue_by_year") %> <%= is_active_graph?("graph_actuals","revenue_by_month")%>">
                      <%= link_to "Revenue/Profit by Year", revenue_by_year_graph_actual_path(current_user.lawfirm_id) %>
                </li>

                <li class="<%=is_active_graph?("graph_actuals","closed_case_load_by_year") %>">
                      <%= link_to "Cases by Practice Group", closed_case_load_by_year_graph_actual_path(params[:range] || 3) %>
                </li>

                <li class="<%=is_active_graph?("graph_actuals","revenue_by_pg") %>">
                      <%= link_to "Fee Received by Practice Group", revenue_by_pg_graph_actual_path(current_user.lawfirm_id) %>
                </li>

                <li class="<%=is_active_graph?("graph_actuals","revenue_by_fee_type") %>">
                      <%= link_to "Fee Received by Fee Type", revenue_by_fee_type_graph_actual_path(current_user.lawfirm_id) %>
                </li>

                <li class="<%=is_active_graph?("graph_actuals","revenue_by_origination") %>">
                      <%= link_to "Fee Received by Origination Source", revenue_by_origination_graph_actual_path(current_user.lawfirm_id) %>
                </li>

                <li class="<%=is_active_graph?("graph_actuals","revenue_by_client") %>">
                      <%= link_to "Client Profitability", revenue_by_client_graph_actual_path(current_user.lawfirm_id) %>
                </li>

                <!-- Consider styling for Practice Groups -->
<!--                 <a href="javascript:;" data-toggle="collapse" data-target="#expected-practicegroups"><i class="fa fa-fw fa-arrows-v"></i> Practice Groups <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="expected-practicegroups" class="collapse">
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                </ul> -->
            </ul>
            <!-- /.End Actual Earnings -->

            <!-- Expected Earnings -->
            <a href="javascript:;" data-toggle="collapse" data-target="#expected"><i class="fa fa-fw fa-arrows-v"></i> Expected Earnings <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="expected" class="collapse">
                <li class="<%=is_active_for_drilldowns?("graph_drilldowns","rev_by_fee_type")%>">
                  <%= link_to "Revenue/Profit by Year", revenue_by_year_path(recovery_rate: 'expected') %>
                </li>

                <li class="<%=is_active_graph?("graphs","practice_group_pie") %>">
                  <%= link_to "Cases by Practice Group", practice_group_cases_path %>
                </li>

                <li class="<%=is_active_graph?("graphs","practice_group_revenue_pie_low") %>">
                  <%= link_to "Fee Received by Practice Group", practice_group_revenue_pie_low_graph_path(current_user.lawfirm_id) %>
                </li>

                <li class="<%=is_active_graph?('graphs','rev_by_year_by_pg')%> or <%=is_active_graph?('graphs','rev_by_year_by_pg_high')%> or <%=is_active_graph?('graphs','rev_by_year_by_pg_low')%>">
                  <%= link_to "Fee Received by Practice Group by Year", revenue_by_year_practice_group_path %>
                </li>

                <li class="<%=is_active_graph?("graphs","rev_by_fee_type_medium")%> <%=is_active_graph?("graphs","rev_by_fee_type_high")%> <%=is_active_graph?("graphs","rev_by_fee_type_low")%>">
                  <%= link_to "Fee Received by Fee Type", revenue_by_year_fee_type_medium_path %>
                </li>

                <li class="<%=is_active_graph?('graphs','fee_received_by_referral_medium')%>">
                  <%= link_to "Fee Received by Origination Source", revenue_by_origination_path %>
                </li>

                <li class="<%=is_active_graph?('graphs','revenue_by_client_estimate')%>">
                  <%= link_to "Client Profitability", revenue_by_client_estimate_graph_path(params[:client_id] || current_user.lawfirm.clients.first, params[:timing] || "estimated_conclusion_expected") %>
                </li>

<!--                 <li class="<%= is_active_graph?("graph_individual_prac_groups","expected_individual_pg_rev") %> dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Practice Groups <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu" id="individualPracticeGroups">

                  </ul>
                <li> -->
            </ul>
            <!-- End Expected -->
        </li>
    </ul>
</div>

app/views/shared/_subheader.html.erb
<br>
<br>
<div id='subheader'>


   <ul class="nav nav-tabs nav-justified" role='tablist'>
      <li id="fat-menu" class="<%= is_active?('cases') %> dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Info</a>
         <ul class="dropdown-menu">
            <% if @case  %>
               <li>
                  <%= link_to "Show Case Info", client_case_path(@case.client_id,@case) %>
               </li>
               <li>
                  <%= link_to "Update Case Info", edit_client_case_path(@case.client_id,@case) %>
               </li>
            <% else %>
               <li>
                  <%= link_to "Add Case Info", new_client_case_path(@case.client_id) %>
               </li>
            <%end%>
         </ul>
      </li>
      <li id="fat-menu" class="<%= is_active?('fees') %> dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Fee</a>
         <ul class="dropdown-menu">
            <% if @case.fees.any?  %>
               <li>
                  <%= link_to "Current Fee", client_case_fee_path(@case.client_id,@case,@case.fees.last) %>
               </li>
               <li>
                  <%= link_to "Fee Timeline", client_case_fees_path(@case.client_id,@case) %>
               </li>
               <li>
                  <%= link_to "Update Fee Estimate", new_client_case_fee_path(@case.client_id,@case) %>
               </li>
            <% else %>
               <li>
                  <%= link_to "Add Case Fee", new_client_case_fee_path(@case.client_id,@case) %>
               </li>
            <%end%>
         </ul>
      </li>
      <li id="fat-menu" class="<%= is_active?('staffs') %> dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff</a>
         <ul class="dropdown-menu">
            <% if @case.staffs.any?  %>
               <li>
                  <%= link_to "Show Staff", client_case_staffs_path(@case.client_id,@case) %>
               </li>
               <li>
                  <%= link_to "Add Staff", new_client_case_staff_path(@case.client_id,@case) %>
               </li>
            <% else %>
               <li>
                  <%= link_to "Add Staff", new_client_case_staff_path(@case.client_id,@case) %>
               </li>
            <%end%>
         </ul>
      </li>
      <li id="fat-menu" class="<%= is_active?('timings') %> dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Timing</a>
         <ul class="dropdown-menu">
            <% if @case.timings.any?  %>
               <li>
                  <%= link_to "Current Timing", client_case_timing_path(@case.client_id,@case,@case.timings.last.id) %>
               </li> <li>
                  <%= link_to "Timing Timeline", client_case_timings_path(@case.client_id,@case) %>
               </li>
               <li>
                  <%= link_to "Update Timing", new_client_case_timing_path(@case.client_id,@case) %>
               </li>
            <% else %>
               <li>
                  <%= link_to "Add Case Timing", new_client_case_timing_path(@case.client_id,@case) %>
               </li>
            <%end%>
         </ul>
      </li>
      <li id="fat-menu" class="<%= is_active?('originations') %> dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Origination</a>
         <ul class="dropdown-menu">
            <% if @case.originations.any?  %>
               <li>
                  <%= link_to "Show Origination", client_case_origination_path(@case.client_id,@case,@case.originations.first.id) %>
               </li>
               <li>
                  <%= link_to "Update Origination", edit_client_case_origination_path(@case.client_id,@case,@case.originations.first.id) %>
               </li>
            <% else %>
               <li>
                  <%= link_to "Add Case Origination", new_client_case_origination_path(@case.client_id,@case) %>
               </li>
            <%end%>
         </ul>
      </li>

      <li class="<%= is_active?('matters') %> dropdown">
         <%= link_to "Matter Types", client_case_matters_path(@case.client_id,@case.id) %>
      </li>

      <li class="<%= is_active?('related_cases') %> dropdown">
         <%= link_to "Related Cases", client_case_related_cases_path(@case.client_id,@case.id) %>
      </li>

      <li id="fat-menu" class="<%= is_active?('checks') %> dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Conflicts</a>
         <ul class="dropdown-menu">
            <% if @case.checks.any?  %>
               <li>
                  <%= link_to "Show Conflicts & Letters", client_case_check_path(@case.client_id,@case,@case.checks.first.id) %>
               </li>
               <li>
                  <%= link_to "Update Conflicts & Letters", edit_client_case_check_path(@case.client_id,@case,@case.checks.first.id) %>
               </li>
            <% else %>
               <li>
                  <%= link_to "Add Conflicts & Letters", new_client_case_check_path(@case.client_id,@case) %>
               </li>
            <%end%>
         </ul>
      </li>


      <% if !@case.closeouts.any? %>
         <li class="<%= is_active?('closeouts') %> dropdown">
            <%= link_to "Closeout", new_client_case_closeout_path(@case.client_id,@case) %>
         </li>
      <% else %>
         <li class="<%= is_active?('closeouts') %> dropdown">
            <%= link_to "Closeout", client_case_closeouts_path(@case.client_id,@case) %>
         </li>
      <% end %>

   </ul>

</div>

<div class='center'>
   <h3><%= @case.name %> </h3>
</div>
<br>


<script type="text/javascript">
   $('ul.nav li.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(150).fadeIn();
   }, function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(150).fadeOut();
   });
</script>