config/routes.rb
Claregal::Application.routes.draw do

  root 'static_pages#index'

  match '/new_subscriber',     to: 'subscribers#create',      via: 'post'

  match '/signup',             to: 'users#new',               via: 'get'
  match '/signin',             to: 'sessions#new',            via: 'get'
  match '/signout',            to: 'sessions#destroy',        via: 'delete'
  match '/joinlawfirm',        to: 'lawfirm_sessions#new',    via: 'get'   #route for joinin lawfirm
  match '/joinlawfirm/commit', to: 'lawfirm_sessions#create', via: 'post'


  #----------------------------------------------------------------------#
  get '/settlement_calculators', to: "settlement_calculators#calculate", as: :calculate

  resources :sessions,                only: [:new, :create, :destroy]
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: [:new, :create, :edit, :update]
  resources :lawfirm_password_resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :lawfirms do
      member do
        get :index_lawfirm_users
        post :toggle_dashboard
      end
      resources :practicegroups do
        member do
          get :group_case_list
        end
      end
      resources :staffings
      resources :case_types
      resources :overheads
    end
  end
  match '/staffings/import',    to: "staffings#import_staffing", via: 'post'
  match '/clients/import',      to: "clients#import_clients",    via: 'post'
  match '/matter_types/import', to: "case_types#import_matters", via: 'post'

  resources :clients do
    resources :cases do
      resources :staffs
      resources :fees
      resources :timings
      resources :originations
      resources :venues
      resources :checks
      resources :closeouts
      resources :matters
      resources :related_cases
    end
  end

  match '/new_case',               to: 'cases#new_case',          via: 'get' #for creating a new case directly, more ux friendly
  match '/new_case/create',        to:'cases#create_case',        via: 'get' #same as above
  match '/new_case/create',        to:'cases#create_case',        via: 'post' #same as above
  match '/new_closed_case',        to: 'cases#new_closed_case',   via: 'get' #for creating a new closed case directly, more ux friendly
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'get' #same as above
  match '/new_closed_case/create', to:'cases#create_closed_case', via: 'post' #same as above

  match '/lawfirm/cases',          to: 'lawfirms#show_lawfirm_cases', via: 'get' #to show current_user.lawfirm.cases
  match '/user/cases',             to:  'cases#user_cases',       via: 'get' #show all cases of current_user
#--------------------------Actual GRAPH ROUTES----------------------------------------------------

  get   'dashboard',                               to: "graphs#dashboard"

  resources :graph_actuals do
    member do
      get :revenue_by_year
      get :revenue_by_pg
      get :revenue_by_fee_type
      get :revenue_by_origination
      get :revenue_by_client
      get :closed_case_load_by_year
      get :individual_practice_group
      get "/revenue_by_month/:year/", to: :revenue_by_month, as: "revenue_by_month"
      get :revenue_by_attorney
    end
  end

  #--------------------------Expected GRAPH ROUTES----------------------------------------------------
  resources :graphs do
    member do
      get :revenue_by_client_estimate
      get :revenue_by_attorney_estimate
      get :practice_group_revenue_pie_low
    end
  end

  match '/practice_group/cases',                   to: "graphs#practice_group_pie",             via: 'get'
  match '/practice_group/:id/revenue',             to: "graph_individual_prac_groups#expected_individual_pg_rev", as: 'expected_individual_pg_rev', via: 'get'

  match '/revenue_by_year/practice_group',         to: "graphs#rev_by_year_by_pg",          via: 'get'
  match '/revenue_by_year/practice_group/high',    to: "graphs#rev_by_year_by_pg_high",     via: 'get'
  match '/revenue_by_year/practice_group/low',     to: "graphs#rev_by_year_by_pg_low",      via: 'get'

  match '/revenue_by_year/fee_type/medium',        to: 'graphs#rev_by_fee_type_medium',     via: 'get'
  match '/revenue_by_year/fee_type/high',          to: 'graphs#rev_by_fee_type_high',       via: 'get'
  match '/revenue_by_year/fee_type/low',           to: 'graphs#rev_by_fee_type_low',        via: 'get'

  match '/revenue_by_origination',                 to: 'graphs#fee_received_by_referral_medium', via: 'get'


  match '/revenue_by_year',                 to: 'graph_drilldowns#rev_by_year',             via: 'get'
  match '/revenue_year',                    to: 'graph_drilldowns#rev_year',                via: 'get'

  #I do not know why this is here, but when I remove it everything breaks
  match '/revenue_by_referral_source',      to: 'graphs#rev_by_fee_type_medium',            via: 'get'

end

app/models/practicegroup.rb
class Practicegroup < ActiveRecord::Base
  belongs_to :lawfirm

  validates :lawfirm_id, :group_name, presence: true
  validates :group_name, uniqueness: {scope: :lawfirm_id}

end

app/controllers/practicegroups_controller.rb
class PracticegroupsController < ApplicationController
  before_action :signed_in_user, :belongs_to_firm

  def new
    @prac_group = Practicegroup.new
    @lawfirm = Lawfirm.find(params[:lawfirm_id])
  end

  def index
    @lawfirm = Lawfirm.find(params[:lawfirm_id])
    @practice_groups = current_user.lawfirm.practicegroups.load
  end

  def group_case_list
    @practice_group = Practicegroup.find(params[:id])
    @cases = Case.where(practicegroup_id: @practice_group.id)
  end

  def create
    @lawfirm = current_user.lawfirm
    @prac_group = @lawfirm.practicegroups.new(practicegroup_params)
    if @prac_group.save
      flash[:success] = "Practice Group Added Succesfully."
      redirect_to user_lawfirm_practicegroups_path(current_user,@lawfirm)
    else
      render 'new'
    end
  end

  def show
    @lawfirm = Lawfirm.find(params[:lawfirm_id])
    @prac_group = Practicegroup.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @lawfirm = Lawfirm.find(params[:lawfirm_id])
    @prac_group = Practicegroup.find(params[:id])
  end

  def update
    @lawfirm = Lawfirm.find(params[:lawfirm_id])
    @prac_group = @lawfirm.practicegroups.find(params[:id])
    if @prac_group.update_attributes(practicegroup_params)
      flash[:success] = "Updated Group Name Successfully"
      redirect_to user_lawfirm_practicegroups_path(current_user,@lawfirm)
    else
      render 'edit'
    end
  end

  private

    def practicegroup_params
      params.require(:practicegroup).permit(:group_name)
    end

end

app/views/practicegroups/edit.html.erb
<% provide(:title, "Edit Group Name") %>
<h2>Edit Group Name</h2>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for(@prac_group, url: {action: "update"}, html: { class: "form-horizontal" }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

       <div class="form-group">
          <div class="col-sm-3">
            <%= f.label :group_name, "Practice Group Name:", class: "control-label" %>
          </div>
          <div class="col-sm-9">
            <%= f.text_field :group_name, class: "form-control" %>
          </div>
        </div>
      <div class="center">
       <%= f.submit "Update Group Name", class: "btn btn-large btn-primary" %>
     </div>
    <% end %>
  </div>
</div>

app/views/practicegroups/group_case_list.html.erb
<% provide(:title, "Practice Groups Case list") %>

<h2>Case List for <%= "#{@practice_group.group_name}" %></h2>


<table id="practiceGroupCaseList" class="display">
  <thead>
    <tr>
      <th>Case Name</th>
      <th>Open?</th>
      <th>Responsible Attorney</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <% @cases.each do |ca| %>
        <tr>
          <td><%= link_to ca.name, client_case_path(ca.client_id,ca.id) %></td>
          <td><%= ca.open == true ? "Open" : "False" %></td>
          <td><%= Case.lead_attorney(ca) %></td>
          <td><%=  %></td>
          <td><%=  %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/practicegroups/index.html.erb
<% provide(:title, "Practice Groups") %>

<h2>Practice Groups for <%= "#{@lawfirm.firm_name}" %></h2>


<table id="lawfirmPracticeGroups" class="display">
  <thead>
    <tr>
      <th>Practice Group Name</th>
      <th>Case Listing</th>
      <th>Actual Profit</th>
      <th>Projected Profit</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <% @practice_groups.each do |group| %>
        <tr>
          <td><%= group.group_name %></td>
          <td><%= link_to "Cases", group_case_list_user_lawfirm_practicegroup_path(current_user.id, current_user.lawfirm_id, group.id) %></td>
          <td><%= link_to "Actual Profit", individual_practice_group_graph_actual_path(group.id) %></td>
          <td><%= link_to "Projected Profit", expected_individual_pg_rev_path(group.id) %></td>
          <td><%= link_to "Edit", edit_user_lawfirm_practicegroup_path(:user_id => current_user.id, :lawfirm_id => current_user.lawfirm.id, :id => group.id) %></td>
        </tr>
      <% end %>
  </tbody>
</table>



<div class='center'>
  <%= link_to "Add Practice Group", new_user_lawfirm_practicegroup_path(:user_id => current_user.id, :lawfirm_id => current_user.lawfirm_id), class: 'btn btn-md btn-primary' %>
</div>

app/views/practicegroups/new.html.erb
<% provide(:title, "New Practice Group") %>

<h2>Add Practice Group to <%= "#{@lawfirm.firm_name}" %> </h2>

<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <%= form_for(@prac_group, url: {action: "create"}, html: {class: "form-horizontal"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>


       <div class="form-group">
          <div class="col-sm-3">
            <%= f.label :group_name, "Practice Group Name:", class: "control-label" %>
          </div>
          <div class="col-sm-9">
            <%= f.text_field :group_name, class: "form-control" %>
          </div>
        </div>

        <div class="center">
         <%= f.submit "Add Practice Group", class: "btn btn-md btn-primary" %>
        </div>
    <% end %>
  </div>
</div>